# -*- coding: utf-8 -*-
"""mugesera detecting  speech

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15y9qev_0cDCLuKLX3kiXCeFkjcyjAFGe
"""

offensive_words = ["inyenzi", "cockroaches", "kill", "exterminate", "destroy",
    "traitors", "snakes", "rats", "hutu power", "tutsi",
    "ethnic cleansing", "wipe out", "enemy", "revenge",
    "impurity", "traitors", "infiltrators", "parasites"]


def detect_hate_speech(text):
    detected_words = [word for word in offensive_words if word in text.lower()]
    return detected_words


text = "I recently said to someone who was boasting about being in the PL [Parti liberal (Liberal Party), pro-Tutsi]: ‘The mistake we made in 1959, even though I was a child then, was that we let you leave.’ I asked him if he hadn’t heard the story of the Falashas who returned to their home in Israel from Ethiopia? He said he did not know this story. I said to him: ‘Don’t you know how to listen or read? Let me tell you that your home is in Ethiopia, and that we will send you back along the Nyabarongo river so you get there quickly.."
hate_words = detect_hate_speech(text)
if hate_words:
    print("Hate speech detected! Offensive words:", hate_words)
else:
    print("No hate speech detected.")