# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZeC4EnGpFLrq89Fg9szLsYVNa91OotfT
"""

from cryptography.fernet import Fernet

key = Fernet.generate_key()

cipher_suite = Fernet(key)

message = b"Names: David Mugisha"

encrypted_message=cipher_suite.encrypt(message)

print("ENCRYPTED MESSAGE:",encrypted_message)

decrypted_message=cipher_suite.decrypt(encrypted_message)

print("Decrypted message:", decrypted_message.decode())